blog/urls.py
from django.conf.urls import url

from . import views

app_name='blog'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^posts/(?P<id>[0-9]+)$', views.show, name='show'),
]

mysite/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls import url, include, handler404
from django.contrib import admin


from . import views

handler404 = 'mysite.views.handler404'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^blog/', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

blog/models.py
from django.db import models


class TimestampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add= True)
    updated_at = models.DateTimeField(auto_now= True)

    class Meta: 
        abstract = True


# Create your models here.
class Post(TimestampedModel):
    title = models.CharField(max_length=255)
    body = models.TextField()
    

def __str__(self):
    return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404

#from .mocks import Post

from .models import Post

# Create your views here.
def index(request):
    posts = Post.objects.all()
    return render(request, 'blog/index.html', {'posts': posts})

def show(request, id):
    post = get_object_or_404(Post, pk=id)
    #Autre solution :
    #try:
    #    post = Post.objects.get(pk=id)
    #except Post.DoesNotExist:
    #    raise Http404('Oups : le post #{} est introuvable !'.format(id))
    return render(request, 'blog/show.html', {'post': post})

mysite/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'pages/home.html')

def about(request):
    return render(request, 'pages/about.html')

def contact(request):
    return render(request, 'pages/contact.html')

def handler404(request, exception=None):
    return render(request, 'errors/404.html', {'error':exception}, status=404)

blog/templates/blog/base.html
{% extends 'layouts/base.html'%}

{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/styles.css' %}">
{% endblock %}


{% block content%}
    <h1>Blog</h1>
    {% block body %} {% endblock %}
{%endblock%}

blog/templates/blog/index.html
{% extends 'blog/base.html'%}


{% block title%}Blog | Mon site{%endblock%}


{% block body%}
<h1>{{ posts|length}} posts</h1>
    {% for post in posts %}
        <article>
            <h2 class="title">
                <a href='{%url 'blog:show' id=post.id%}'>#{{post.id}} - {{post.title|upper}}<a/>
            </h2>
            <p class="time"><time datetime="{{post.created_at|date:'d-m-Y'}}"> Posté il y a {{post.created_at|timesince}}</time></p>
            <p class="body">{{post.body|truncatewords:3}}</p>
        </article>
        {% empty %}
        <p>Sorry, no posts available</p>
    {% endfor %}
{% endblock %}

blog/templates/blog/show.html
{% extends 'blog/base.html' %}

{% block title%}Blog | {{post.title}}{% endblock %}

{% block body %}
    <article>
    <h1 class="title">#{{post.id}} - {{post.title}}</h1>
    <p class="body">{{post.body}}</p>
    </article>
<hr>
<p><a href="{% url 'blog:index'%}">All posts</a></p>
{% endblock %}

templates/layouts/_footer.html
<footer class="footer text-center">
    <p>&copy; Copyright {% now 'Y'%} &middot; Anaïs &middot; All rights reserved !</p>
</footer>

templates/layouts/_nav.html
<nav class="navbar">
 <div class="wrapper">
    <a href="{%url 'home'%}" class="navbar-brand">Mysite</a>
    <ul class="navbar-right">
        <li><a href="{% url 'home'%}">Home</a></li>
        <li><a href="{% url 'about'%}">About</a></li>
        <li><a href="{% url 'contact'%}">Contact</a></li>
        <li><a href="{% url 'blog:index'%}">Blog</a></li>
    </ul>
 </div>
</nav>

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <title>{% block title %}My site {% endblock %}</title>
    {% block stylesheets %}{% endblock %}
</head>
<body>
    {% include 'layouts/_nav.html'%}

    <div class="wrapper">
    {% block content%} {%endblock%}
    </div>
    {% include 'layouts/_footer.html'%}
</body>
</html>

templates/pages/about.html
{% extends 'layouts/base.html'%}

{% block title%}About{%endblock%}

{% block content%}
    <h1>About</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio quae blanditiis voluptas, aliquid magni, sequi deleniti necessitatibus asperiores perspiciatis doloribus vel ut voluptatem distinctio commodi quidem molestias quaerat nisi minus.</p>
{%endblock%}

templates/pages/contact.html
{% extends 'layouts/base.html'%}

{% block title%}Contact{%endblock%}

{% block content%}
<h1>Formulaire contact</h1>
{%endblock%}

templates/pages/home.html
{%extends 'layouts/base.html'%}


{% block content%} 
    <h1>Hello Mysite !</h1>
    <p><a href='{%url 'blog:index'%}'>Visiter le blog</a></p>
{%endblock%}